version: 2
multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
      day: saturday
updates:
  - package-ecosystem: npm
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    cooldown:
      default-days: 1
  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: dependencies
    cooldown:
      default-days: 1
